workflows:
  ios-capacitor-build:
    name: iOS Capacitor Build
    max_build_duration: 60
    environment:
      groups:
        - app_store_credentials
      node: 22
      xcode: latest
    scripts:
      - name: Installa dipendenze e sincronizza Capacitor
        script: |
          npm install
          npm run build
          npx cap sync ios
      - name: Configura il Code Signing automatico
        script: |
          keychain initialize
          app-store-connect fetch-signing-files "co.median.ios.mbbline" --type IOS_APP_STORE --create
          keychain add-certificates
      - name: Allinea Bundle Identifier nel progetto Xcode
        script: |
          sed -i '' 's/PRODUCT_BUNDLE_IDENTIFIER = .*/PRODUCT_BUNDLE_IDENTIFIER = co.median.ios.mbbline;/g' ios/App/App.xcodeproj/project.pbxproj
      - name: Genera Export Options e applica profili
        script: |
          xcode-project use-profiles
      - name: Compila l'applicazione iOS
        script: |
          xcode-project build-ipa \
            --project "ios/App/App.xcodeproj" \
            --scheme "App"
    artifacts:
      - build/ios/ipa/App.ipa
    publishing:
      app_store_connect:
        auth: integration
        submit_to_testflight: true
